name: 'Resharper InspectCode Action'
author: 'Pavel (Jayzzer) Pushkarev'
description: 'Simple action that runs the InspectCode utility from JetBrains'
branding:
  icon: 'code'
  color: 'green'
inputs:
  solution:
    description: 'Path to solution file'
    required: true
  project:
    description: 'Name of the project to analyze'
  profile:
    description: 'Path to project DotSettings'
  build:
    description: 'let you specify whether to build the target solution before starting the analysis'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.solution }}
    - '--project="${{ inputs.project }}"'
    - '--profile="${{ inputs.profile }}"'
    - '--build="${{ inputs.build }}"'
    - '-o=report.xml'
